<a href="https://colab.research.google.com/github/HusainAhmadKhan/Python-Practise/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy #In google colab it is already installed so no need to write this commad, use this in IDE

In [ ]:
import numpy as np #This is to import numpy

In [ ]:
lst=[1,2,3,4,5,6,7,8,9,10]
print(type(lst))

<class 'list'>


In [ ]:
lst=[1,2,3,4,5,6,7,8,9,10]
print(type(lst))
arr1d= np.array(lst)
type(arr1d)

<class 'list'>


numpy.ndarray

In [ ]:
arr1d= np.array([1,2,3,4,5,6,7,8,9,10])
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Numpy supports vectorized operation, while list doesn't support this
#NumpyArray is faster and supports more functionality
arr1d= np.array([1,2,3,4,5,6,7,8,9,10])
arr1d*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
lst=[1,2,3,4,5,6,7,8,9,10]
arr1d= np.array(lst)
print(arr1d*2)
print(arr1d+arr1d)
print(arr1d-arr1d)
print(lst*2)#List repetiton is performed, no vectorized operation
print(lst+lst)#List concatenation is performed, no addition
#print(lst-lst) We can't subtract

[ 2  4  6  8 10 12 14 16 18 20]
[ 2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
lst=[1,2,3,4,5,6,7,8,9,10]

print(lst*2)#Repetition
#print(lst+2)#List doesn't support this
#print(lst-2)#List doesn't support this
#print(lst/2)#List doesn't support this
#print(lst%2)#List doesn't support this

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
lst=[1,2,3,4,5,6,7,8,9,10]
arr1d= np.array(lst)
print(arr1d*2)#All values *2
print(arr1d+2)#All values +2
print(arr1d-2)#All values -2
print(arr1d/2)#All values /2
print(arr1d%2)#All values %2
print(arr1d.size)#Tells the size of array
print(arr1d.ndim)#Tells number of dimensions   #Horizontal rows= 1 dimensional,  Multiple rows/images= 2 dimensional
print(arr1d.shape)#Tells the width and height  #Tells the structure of the matrix




[ 2  4  6  8 10 12 14 16 18 20]
[ 3  4  5  6  7  8  9 10 11 12]
[-1  0  1  2  3  4  5  6  7  8]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
[1 0 1 0 1 0 1 0 1 0]
10
1
(10,)


In [ ]:
#Using numpy arange
#arange works like range (starting: end: steps)  #last one is exclusive
lst=[1,2,3,4,5,6,7,8,9,10]
arr1d= np.array(lst)
arr1d=np.arange(10)
print(arr1d)
arr1d=np.arange(1,5)
print(arr1d)
arr1d=np.arange(2,10,2)
print(arr1d)
print(arr1d[0])
print(arr1d[-1])

[0 1 2 3 4 5 6 7 8 9]
[1 2 3 4]
[2 4 6 8]
2
8


In [ ]:
#2dArray from python list
lst2d=[[1,2,3],
       [11,22,33],
       [111,222,333]]

print(lst2d)
print(type(lst2d))

[[1, 2, 3], [11, 22, 33], [111, 222, 333]]
<class 'list'>


In [ ]:
#2dArray from python list
lst2d=[[1,2,3],
       [11,22,33],
       [111,222,333]]
arr2d=np.array(lst2d)
print(arr2d)
print(type(arr2d))
print(arr2d.size)
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d[0][0])
print(arr2d[-1][-1])#333 is output  #First one is for row, second is for column-->> confirm this
print(arr2d[-1][-2])#222 is output
print(arr2d[-2][-3])#11 is output



[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
<class 'numpy.ndarray'>
9
2
(3, 3)
1
333
222
11


In [ ]:
#Using arange with reshape
lst2d=[[1,2,3],
       [11,22,33],
       [111,222,333]]
arr2d=np.arange(36).reshape(4,9) #4*9=36 acceptable, no error
# arr2d=np.arange(36).reshape(5,5) #5*5=25 which is not equal to 36 in arange so not acceptable, there will be error
print(arr2d)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]


In [ ]:
lst2d=[[1,2,3],
       [11,22,33],
       [111,222,333]]
arr2d=np.arange(300).reshape(15,20)
print(arr2d)


[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]
 [200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
  218 219]
 [220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235

In [ ]:
#Factors
lst2d=[[1,2,3],
       [11,22,33],
       [111,222,333]]
arr2d=np.arange(36).reshape(4,9)
print(arr2d)
print("Gap")
arr2d=np.arange(36).reshape(9,4)
print(arr2d)
print("Gap\n")
arr2d=np.arange(36).reshape(6,6)
print(arr2d)
print("Gap\n")
arr2d=np.arange(36).reshape(12,3)
print(arr2d)
print("Gap\n")
arr2d=np.arange(36).reshape(3,12)
print(arr2d)
print("Gap\n")
arr2d=np.arange(36).reshape(2,18)
print(arr2d)
print("Gap\n")
arr2d=np.arange(36).reshape(18,2)
print(arr2d)
print("Gap\n")
arr2d=np.arange(36).reshape(36,1)
print(arr2d)
print("Gap\n")
arr2d=np.arange(36).reshape(1,36)
print(arr2d)


[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]
Gap
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]
Gap

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Gap

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]
 [27 28 29]
 [30 31 32]
 [33 34 35]]
Gap

[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]]
Gap

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]]
Gap

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]]
Gap

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]

In [ ]:
#Array of 150 elements which is 2 dimensional
lst2d=[[1,2,3],
       [11,22,33],
       [111,222,333]]
arr2d=np.arange(150).reshape(15,10)
print(arr2d)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]]


In [ ]:
lst=[1,2,3,4,5,6,7,8,9,10]
arr1d=np.array(lst)
print(arr1d[7])
print(arr1d[4:8]) #Index start from 0


8
[5 6 7 8]


In [ ]:
lst2d=[[1,2,3],
       [11,22,33],
       [111,222,333]]
arr2d=np.arange(36).reshape(4,9)
print(arr2d)


[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]


In [ ]:
#arr2d[row,col] >>> [startrow: endrow][start col:endcol]
print(arr2d[2][5])
print(arr2d[2,5])#This can also be written as print(arr2d[2][5])
print(arr2d[-1][0])
print(arr2d[-2][-1])
print(arr2d[3][1])
print(arr2d[1:2]) #First row aajayegi
print(arr2d[1:3]) #First tow rows aajeyngi
print(arr2d[1:3, 5:])#First two rows and from 5th index to last index of every row mentioned
print(arr2d[1:, 0:3])

23
23
27
26
28
[[ 9 10 11 12 13 14 15 16 17]]
[[ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]
[[14 15 16 17]
 [23 24 25 26]]
[[ 9 10 11]
 [18 19 20]
 [27 28 29]]


In [ ]:
print(arr2d[0:4, 6:9])
print("gap\n")
print(arr2d[1:3, 5:7])
print("gap\n")
print(arr2d[:, 6:])
print("gap\n")
print(arr2d[2, 4:7])
print("gap\n")
print(arr2d[:,-1])
print("gap\n")
print(arr2d[:,8:])
print("gap\n")
print(arr2d[:, ::3])
print("gap\n")
print(arr2d[:, ::-2])


[[ 6  7  8]
 [15 16 17]
 [24 25 26]
 [33 34 35]]
gap

[[14 15]
 [23 24]]
gap

[[ 6  7  8]
 [15 16 17]
 [24 25 26]
 [33 34 35]]
gap

[22 23 24]
gap

[ 8 17 26 35]
gap

[[ 8]
 [17]
 [26]
 [35]]
gap

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]
 [27 30 33]]
gap

[[ 8  6  4  2  0]
 [17 15 13 11  9]
 [26 24 22 20 18]
 [35 33 31 29 27]]


In [ ]:
#3dArray  Three Dimensional
arr3d=np.arange(64).reshape(4,4,4)
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


In [ ]:
#200 elements 3d array
arr3d=np.arange(200).reshape(5,5,8)
print(arr3d)
print(arr3d.size)
print(arr3d.shape)
print(arr3d.ndim)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]]

 [[ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]
  [ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]]

 [[ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]
  [112 113 114 115 116 117 118 119]]

 [[120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]]

 [[160 161 162 163 164 165 166 167]
  [168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]]]
200
(5, 5, 8)
3


In [ ]:
#Vectorized Operation on 3d Array
print(arr3d*2)
print(arr3d+2)
print(arr3d-2)
print(arr3d/2)
print(arr3d%2)

[[[  0   2   4   6   8  10  12  14]
  [ 16  18  20  22  24  26  28  30]
  [ 32  34  36  38  40  42  44  46]
  [ 48  50  52  54  56  58  60  62]
  [ 64  66  68  70  72  74  76  78]]

 [[ 80  82  84  86  88  90  92  94]
  [ 96  98 100 102 104 106 108 110]
  [112 114 116 118 120 122 124 126]
  [128 130 132 134 136 138 140 142]
  [144 146 148 150 152 154 156 158]]

 [[160 162 164 166 168 170 172 174]
  [176 178 180 182 184 186 188 190]
  [192 194 196 198 200 202 204 206]
  [208 210 212 214 216 218 220 222]
  [224 226 228 230 232 234 236 238]]

 [[240 242 244 246 248 250 252 254]
  [256 258 260 262 264 266 268 270]
  [272 274 276 278 280 282 284 286]
  [288 290 292 294 296 298 300 302]
  [304 306 308 310 312 314 316 318]]

 [[320 322 324 326 328 330 332 334]
  [336 338 340 342 344 346 348 350]
  [352 354 356 358 360 362 364 366]
  [368 370 372 374 376 378 380 382]
  [384 386 388 390 392 394 396 398]]]
[[[  2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17]
  [ 18  19  20  21

In [ ]:
#Find 50 through slicing
print(arr3d[1,1,2])

50
