<a href="https://colab.research.google.com/github/HusainAhmadKhan/Python-Practise/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Syntax is np.zeros(size, type)  not neccessary to give a type, size should be given.
#Most answers in numpy are in float
#np.zeros gives answer in float by default
print(np.zeros(10)) #Output: Array of length 10 all 0 in  float
print(np.zeros(10, dtype="int")) #This displays in integer
print(np.zeros(10, dtype="bool")) #This displays in bool. All False
print(np.zeros(10, dtype="complex")) #This displays in complex.
print(np.zeros(10, dtype="str")) #This displays in string.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[False False False False False False False False False False]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
['' '' '' '' '' '' '' '' '' '']


In [ ]:
print(np.zeros((4,5))) #This is a tuple passed here. tuple is (4,5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.zeros((4,4,4), dtype="int")) #This is a three dimensional array in integer

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
print(np.ones(10)) #Output: Array of length 10 all 0 in  float
print(np.ones(10, dtype="int")) #This displays in integer
print(np.ones(10, dtype="bool")) #This displays in bool. All True
print(np.ones(10, dtype="complex")) #This displays in complex.
print(np.ones(10, dtype="str")) #This displays in string.

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[ True  True  True  True  True  True  True  True  True  True]
[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]
['1' '1' '1' '1' '1' '1' '1' '1' '1' '1']


In [ ]:
print(np.ones((4,4))) #Two dimensional array

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
print(np.ones((4,4,4), dtype="int")) #Three dimensional array in integer

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
def sum1(a=0, b=0, c=0, d=0):
  print(a)
  print(b)
  print(c)
  print(d)
sum1(1,3,5,7)

1
3
5
7


In [ ]:
print(np.ones((4,4,4,4), dtype="int")) #This displays 4 dimensional array in integer

[[[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]


 [[[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]

  [[1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]
   [1 1 1 1]]]]


In [ ]:
arr2d=np.ones((4,4), dtype="int")  # or arr2d=np.ones((4,4), dtype="int") *10
arr2d=arr2d*10        #If yoy used only arr2d*10 you are not storing it that's why output is in 1
print(arr2d)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [ ]:
print(np.eye(4)) #This prints square matrix 4 X 4 / Identity matrix with diagonals = 1

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
print(np.eye(4,dtype="int")) #This prints square matrix 4 X 4 in integer / Identity matrix with diagonals 1 in integer

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
arr=np.eye(4,dtype="int")*10  #This is a diagonal matrix since diagonals becomes 10
print(arr)


[[10  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  0 10]]


In [ ]:
print(np.eye(4,5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
print(np.eye(7,5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(np.eye(7,5,dtype="int")) #in integer

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
#diagonals start from index 2
print(np.eye(4,5,2)) # Syntax: np.eye(rows, columns, starting index)
# print(np.eye(4,5,2,dtype="int"))  for integer

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#2 Dimensional
arr2d=np.random.randn(3,4) # randn gives random number
print(arr2d)

[[-0.11618485  1.10508806  1.16067229  0.96237235]
 [-2.11391424  2.08440007 -1.24146713 -0.57940938]
 [-0.73212342  0.96150799 -0.22304017 -0.53070296]]


In [ ]:
#1 Dimensional
arr1d=np.random.randn(4)
print(arr1d)

[-0.70047966 -0.68459619 -0.33516247 -2.63911643]


In [ ]:
#3 Dimensional
arr3d=np.random.randn(4,4,4)
print(arr3d)

[[[-1.26792881 -0.22524689 -1.1937425  -0.50677982]
  [ 0.72698061  0.56212426  0.04983799  0.17290212]
  [ 0.50133815 -2.26417691  0.7860237  -0.55917293]
  [ 0.54403873 -1.71082165  0.30270262 -1.03817289]]

 [[-0.32973416  0.93002791 -0.4337507   0.52033709]
  [-0.07404908 -0.1128302  -0.47885703  0.81558881]
  [ 0.3223118  -0.44054869 -0.70372436 -0.21470258]
  [-0.15603736  2.25750077  1.24338977  2.18165821]]

 [[ 0.33510729  0.14903617  2.02422882 -0.07458888]
  [-1.74673488 -0.59861047  0.03264121 -0.11130612]
  [ 0.35968085  0.86791681 -0.64520983 -0.3352688 ]
  [ 0.31233539 -1.24571832  0.13177898 -1.96410149]]

 [[ 1.28845782 -1.1244324  -0.05198833 -1.79431641]
  [ 1.06094184 -2.11746883  1.44096278 -1.68190487]
  [-0.71667653 -1.20062327  0.58728409 -0.89261921]
  [ 0.93721731  1.32613399 -0.00456907 -1.15765386]]]


In [ ]:
arr1d=np.random.randint(4) #randint gives random integer
print(arr1d)

3


In [ ]:
arr2d1=np.arange(12).reshape(3,4)
print(arr2d1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr2d2=np.random.randn(3,4)
print(arr2d2)

[[ 0.54125701  0.5782809  -0.62415527  0.90947204]
 [-0.31655603 -0.56538683  1.97588152  0.72541504]
 [-0.52074303 -1.34672975 -1.27837087  0.77930888]]


In [ ]:
#When adding arrays size should be same
print(arr2d1+arr2d2)

[[ 0.54125701  1.5782809   1.37584473  3.90947204]
 [ 3.68344397  4.43461317  7.97588152  7.72541504]
 [ 7.47925697  7.65327025  8.72162913 11.77930888]]


In [ ]:
print(arr2d1*arr2d2)

[[  0.           0.5782809   -1.24831055   2.72841612]
 [ -1.26622412  -2.82693416  11.85528913   5.07790531]
 [ -4.16594425 -12.12056773 -12.78370871   8.5723977 ]]


In [ ]:
arr3d1=np.arange(27).reshape(3,3,3)
print(arr3d1)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
arr3d2=np.random.randn(3,3,3)
print(arr3d2)

[[[-1.24469372  0.73919511  0.7717432 ]
  [ 0.3532293   0.45021101 -1.24829451]
  [ 0.89628192 -0.94709876  0.72144924]]

 [[-1.97813471  0.68069397  1.37017093]
  [ 0.59950905 -0.49647581  0.17915495]
  [-2.46981844  0.16345049  0.39504987]]

 [[-0.28582408  2.39135893  1.30949012]
  [ 0.17014827  0.66800525 -0.80706492]
  [ 0.67232688 -0.37253239 -0.77297842]]]


In [ ]:
print(arr3d1+arr3d2)

[[[-1.24469372  1.73919511  2.7717432 ]
  [ 3.3532293   4.45021101  3.75170549]
  [ 6.89628192  6.05290124  8.72144924]]

 [[ 7.02186529 10.68069397 12.37017093]
  [12.59950905 12.50352419 14.17915495]
  [12.53018156 16.16345049 17.39504987]]

 [[17.71417592 21.39135893 21.30949012]
  [21.17014827 22.66800525 22.19293508]
  [24.67232688 24.62746761 25.22702158]]]


In [ ]:
print(arr3d1*arr3d2)

[[[ -0.           0.73919511   1.54348639]
  [  1.05968789   1.80084405  -6.24147254]
  [  5.37769155  -6.62969132   5.77159394]]

 [[-17.80321236   6.80693971  15.07188021]
  [  7.1941086   -6.45418553   2.50816926]
  [-37.04727659   2.61520783   6.71584771]]

 [[ -5.14483342  45.43581968  26.18980233]
  [  3.57311377  14.69611553 -18.56249307]
  [ 16.13584516  -9.3133098  -20.09743898]]]


In [ ]:
arr2d1=np.arange(12).reshape(3,4)
print(arr2d1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr2d2=np.random.randn(4,3)
print(arr2d2)

[[ 0.04109678 -0.234083    0.57710844]
 [ 0.70941166  0.28433602  0.97126453]
 [-1.18777918 -0.67300871  2.27251255]
 [ 0.5076937   0.26760199 -0.08546433]]


In [ ]:
# print(arr2d1*arr2d2) #operands could not be broadcast together with shapes (3,4) (4,3)
# print(arr2d1+arr2d2) #operands could not be broadcast together with shapes (3,4) (4,3)

In [ ]:
#Matrix Multiplication
# Column of first == Rows of second (Checking Operation)
# Row of first * Column of second (Multiply Operation)
a=np.arange(10).reshape(5,2)
b=np.arange(10).reshape(2,5)
print(a@b) # @ is used for matrix multiplication

[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


In [ ]:
#Matrix Multiplication
# Column of first == Rows of second (Checking Operation)
# Row of first * Column of second (Multiply Operation)
a=np.arange(10).reshape(5,2)
b=np.random.randn(2,5)
print(a@b) # @ is used for matrix multiplication

[[ 1.22376237  0.46405031 -0.33907379 -1.46952194  1.49072092]
 [ 3.08605502  3.50706331 -2.25660783 -1.44849595  7.73589097]
 [ 4.94834768  6.55007631 -4.17414186 -1.42746997 13.98106103]
 [ 6.81064033  9.59308931 -6.0916759  -1.40644398 20.22623108]
 [ 8.67293299 12.63610231 -8.00920994 -1.385418   26.47140114]]


In [ ]:
a=np.arange(27).reshape(3,3,3)
b=np.random.randn(3,3,3)
print(a@b)

[[[ -2.76766338   0.3585401   -2.02634244]
  [ -7.92968847   4.1286122   -2.49470602]
  [-13.09171356   7.89868429  -2.9630696 ]]

 [[-10.11431189  18.1025082   21.38705632]
  [-13.60945366  24.14367     27.08149055]
  [-17.10459542  30.18483181  32.77592478]]

 [[ 20.14172065  15.35224768 -34.90715125]
  [ 23.27790641  17.94006253 -40.42515384]
  [ 26.41409217  20.52787737 -45.94315642]]]


In [ ]:
np.array([1,2,3]) * np.array([1,2,3])

array([1, 4, 9])

In [ ]:
a=np.arange(10).reshape(5,2)
b=np.random.randn(2,5)
a.dot(b) #dot can also be used for matrix multiplication

array([[ 0.20056484,  2.426363  ,  0.68258023, -1.31425011,  0.71046486],
       [-1.32638039,  4.97074157,  3.97208963, -3.18574596,  5.97193272],
       [-2.85332562,  7.51512014,  7.26159902, -5.05724182, 11.23340059],
       [-4.38027085, 10.05949871, 10.55110841, -6.92873767, 16.49486846],
       [-5.90721607, 12.60387728, 13.84061781, -8.80023353, 21.75633632]])

In [ ]:
#first parameter tells size and second parameter tells value which is filled to whole array
np.full((4,5),10)  #here (4,5) is tuple

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
np.full(4,10)

array([10, 10, 10, 10])

In [ ]:
arr2d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.zeros_like(arr2d1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
arr2d1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.ones_like(arr2d1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])