<a href="https://colab.research.google.com/github/HusainAhmadKhan/Python-Practise/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fancy Indexing

In [ ]:
pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr2d=np.arange(36).reshape(4,9)
print(arr2d)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]


In [ ]:
# [rows:ending, columns:ending]
arr2d[:,[5,8,0,3]]    #all rows, and dispays index 5,8,0,3 of every row


array([[ 5,  8,  0,  3],
       [14, 17,  9, 12],
       [23, 26, 18, 21],
       [32, 35, 27, 30]])

In [ ]:
arr2d[[0,2],[2,7]]  #[0,2]=2 , [2,7]=25   ,  you can't do arr2d[[0,2],[2,7], [2,2]] because it will be 3 dimensional, however you declared above reshape(4,9) which is 2 dimensional

array([ 2, 25])

In [ ]:
arr2d[:, ::3] #steps/alternate, every 3rd index of every row like 0,3,6

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24],
       [27, 30, 33]])

In [ ]:
arr2d[::3, ::3]   #every 3rd row and every 3rd column of that specific row

array([[ 0,  3,  6],
       [27, 30, 33]])

In [ ]:
arr2d[:, ::-2]  #every 2nd index of every row of reverse array  ,  minus(-) means reverse

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [ ]:
arr3d= np.arange(64).reshape(4,4,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [ ]:
print(arr3d[1][2][2])  #this can also be written as arr3d[1,2,2]
#print(arr3d[1,2,2])

26


In [ ]:
print(arr3d[3][1][3])


55


In [ ]:
print(arr3d[3])
print(arr3d[3][1:3])

[[48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]]
[[52 53 54 55]
 [56 57 58 59]]


In [ ]:
#[[52 53 54 55]  this is index 0
#[56 57 58 59]]  this is index 1
#now if you do last[1:3] 1st index which is [56 57 58 59] is displayed and 3rd index doesnt exist which is basically 2 doesnt exist it is not displayed
print(arr3d[3][1:3][1:3])
print(arr3d[3][1:3][2:3]) #the index which doesn't exist is not dispayed.


[[56 57 58 59]]
[]


In [ ]:
print(arr3d[3][1:3][1:3,1:3])

[[57 58]]


In [ ]:
print(arr3d[3][1:3][1:3,1:5])  # since 5 index which is basically 4 doesn't exist therefore till 3rd column it gets printed which is it's last.

[[57 58 59]]


In [ ]:
print(arr3d[3][1:3][1:3,4:5]) ##the index which doesn't exist is not dispayed.

[]


In [ ]:
print(arr3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


In [ ]:
# [frame, rows, columns]
# [fstart:fend , rstart:rend, cstart:cend]
arr3d[3:4, 1:3, 1:3]

array([[[53, 54],
        [57, 58]]])

In [ ]:
print(arr3d[2, 1:5, 1:4])
print("Gap\n")
print(arr3d[1, 2, 2: ])
print("Gap\n")
print(arr3d[1:3, 1:3, 1:1])  #here 1:1 means no value
print("Gap\n")
print(arr3d[1:2, 3, 1:3])
print("Gap\n")

[[37 38 39]
 [41 42 43]
 [45 46 47]]
Gap

[26 27]
Gap

[]
Gap

[[29 30]]
Gap



In [ ]:
#Printing different slicing for 3 dimensional array inside a function
def my_function():
  print(arr3d[3:4, 1:3, 1:3])
  print("Gap\n")
  print(arr3d[2, 1:5, 1:4])
  print("Gap\n")
  print(arr3d[1, 2, 2: ])
  print("Gap\n")
  print(arr3d[1:3, 1:3, 1:1])  #here 1:1 means no value
  print("Gap\n")
  print(arr3d[1:2, 3, 1:3])
  print("Gap\n")

my_function()

[[[53 54]
  [57 58]]]
Gap

[[37 38 39]
 [41 42 43]
 [45 46 47]]
Gap

[26 27]
Gap

[]
Gap

[[29 30]]
Gap

