<a href="https://colab.research.google.com/github/HusainAhmadKhan/Python-Practise/blob/main/NumpyWithTasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Task 1: Creating 1D Arrays**

In [ ]:
#Create a 1D NumPy array of integers from 0 to 19 using arange().
#• Print the array
#• Print its shape
#• Print its data type

arr1d=np.arange(20)
print(arr1d)
print(arr1d.shape)
print(type(arr1d))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
(20,)
<class 'numpy.ndarray'>


**Task 2: 2D Array Manipulation**

In [ ]:
#Create a 2D array of shape (10, 14) using arange().
#• Access the element in 2nd row and 10th column
#• Print the entire eight row
arr2d=np.arange(140).reshape(10,14)
print(arr2d[2][10])
print(arr2d[8])

38
[112 113 114 115 116 117 118 119 120 121 122 123 124 125]


**Task 3: 3D Array Understanding**

In [ ]:
#Create a 3D NumPy array of shape (2, 3, 4).
#• Print number of dimensions
#• Print shape
arr3d=np.arange(24).reshape(2,3,4)
print(arr3d.ndim)
print(arr3d.shape)

3
(2, 3, 4)


**Task 4: Zeros and Ones**

In [ ]:
#Create:
#• 1D array of five zeros
#• 2D array (3x3) of ones
arr1d0=np.zeros(5, dtype="int")
print(arr1d0)
arr2d1=np.ones((3,3), dtype="int")
print(arr2d1)

[0 0 0 0 0]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


**Task 5: zeros_like and ones_like**

In [ ]:
#Given A = np.array([[2, 4, 6], [1, 3, 5]]):
#• Create zeros_like
#• Create ones_like
A = np.array([[2, 4, 6], [1, 3, 5]])
zeros=np.zeros_like(A)
print(zeros)
ones=np.ones_like(A)
print(ones)

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


**Task 6: Vectorized Addition**

In [ ]:
#Create two 1D arrays of size 5.
#• Add them.
arr1d1=np.arange(5)
arr1d2=np.arange(5)
result=arr1d1 + arr1d2
print(result)

[0 2 4 6 8]


**Task 7: Vectorized Multiplication**

In [ ]:
#Create two 2D arrays (2x3).
#• Multiply element-wise
arr2d1= np.arange(6).reshape(2,3)
arr2d2= np.random.randn(2,3)
m_result=arr2d1 * arr2d2
print(m_result)


[[-0.         -0.55910231  0.44308126]
 [ 0.62941955  1.21312541  2.72583652]]


**Task 8: Scalar Operations**

In [ ]:
#Create arange(1,6).
#• Multiply by 5
#• Add 10
arr=np.arange(1,6)
result= (arr * 5) + 10
print(result)


[15 20 25 30 35]


**Task 9: Dot Product (1D)**

In [ ]:
#Create two 1D arrays of size 4.
#• Compute dot product
arr1d1=np.arange(4)
arr1d2=np.arange(4)
result=arr1d1.dot(arr1d2)
print(result)


14


**Task 10: Dot Product (2D)**

In [ ]:
#Create matrices (2x3) and (3x2).
#• Perform matrix multiplication
m1=np.arange(6).reshape(2,3)
m2=np.arange(6).reshape(3,2)
result=m1@m2
print(result)

[[10 13]
 [28 40]]


**Task 11: Real-World Scenario**

In [ ]:
#Math = [78, 85, 90, 88, 76]
#Science = [80, 82, 89, 91, 77]
#• Convert to NumPy arrays
#• Find total marks using element wise operation
Math = [78, 85, 90, 88, 76]
Science = [80, 82, 89, 91, 77]
math_arr=np.array(Math)
science_arr=np.array(Science)
total_marks= math_arr+ science_arr
print(total_marks)


[158 167 179 179 153]


**Task 12: Error Spotting**

In [ ]:
#A = np.arange(10)
#B = np.arange(5)
#C = A + B
#• Identify error
#• Explain why it occurs

#Rows and Columns of a matrix should be same when adding, here it is different
#When adding arrays size should be same

**Task 13: Reshaping Challenge**

In [ ]:
#Create an array of numbers from 1 to 24.
#• Reshape into (4,6)
#• Then reshape into (2,3,4)
arr= np.arange(1,25)
print(arr)
print("\n")
arr1=arr.reshape(4,6)
print(arr1)
print("\n")
arr2=arr.reshape(2,3,4)
print(arr2)



[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Task 14: Broadcasting Logic**

In [ ]:
#Create a (3x3) matrix using arange().
#Create a 1D array of size 3.
#• Add them using broadcasting
#• Explain how broadcasting works

matrix_3x3 = np.arange(9).reshape(3, 3)
array_1d = np.array([10, 20, 30])
result = matrix_3x3 + array_1d

print("3x3 Matrix:\n", matrix_3x3)
print("\n1D Array:\n", array_1d)
print("\nResult of Addition:\n", result)

print("\n")
print("How Broadcasting Works?")
print("Alignment: It aligns the shapes starting from the rightmost dimension.")
print("Virtual Stretching: Since the 1D array has only one row, NumPy \"stretches\" (conceptually duplicates) that row downward until it matches the 3 rows of the matrix.")
print("Element-wise Addition: Now that the shapes are effectively both (3, 3), it adds them normally.")


3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

1D Array:
 [10 20 30]

Result of Addition:
 [[10 21 32]
 [13 24 35]
 [16 27 38]]


How Broadcasting Works?
Alignment: It aligns the shapes starting from the rightmost dimension.
Virtual Stretching: Since the 1D array has only one row, NumPy "stretches" (conceptually duplicates) that row downward until it matches the 3 rows of the matrix.
Element-wise Addition: Now that the shapes are effectively both (3, 3), it adds them normally.


**Task 15: Row-wise Operations**

In [ ]:
#Create a (4x4) matrix using arange().
#• Multiply each row by 2 using vectorization only
arr4d=np.arange(16).reshape(2,2,2,2)
print(arr4d)
print('Gap\n\n')
mul=arr4d*2
print(mul)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
Gap


[[[[ 0  2]
   [ 4  6]]

  [[ 8 10]
   [12 14]]]


 [[[16 18]
   [20 22]]

  [[24 26]
   [28 30]]]]


**Task 16: Column-wise Scaling**

In [ ]:
#Create a (3x3) matrix.
#Create a 1D array of size 3.
#• Multiply each column by corresponding value using broadcasting
matrix_3x3 = np.arange(9).reshape(3,3)
array_1d = np.arange(3)
result = matrix_3x3 * array_1d
print(result)


[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]


**Task 17: 3D Computation**

In [ ]:
#Create a 3D array (2x3x4).
#• Add 5 to all elements
#• Multiply entire array by 3
arr3d=np.arange(24).reshape(2,3,4)
print(arr3d)
print("gap\n\n")
add3d=arr3d+5
print(add3d)
print("gap\n\n")
mul3d=add3d*3
print(mul3d)



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
gap


[[[ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]]]
gap


[[[15 18 21 24]
  [27 30 33 36]
  [39 42 45 48]]

 [[51 54 57 60]
  [63 66 69 72]
  [75 78 81 84]]]
